/* T4 Sprite Creator written by Kornél Regius (www.cornelius.hu) based on:
    CPOL Image Sprite Creator V2.0 by AlexCode http://www.codeproject.com/script/Membership/View.aspx?mid=361529
    http://www.codeproject.com/Articles/140251/Image-Sprites-and-CSS-Classes-Creator
    And CPL by Copyright (C) 2002-2011 Nuclex Development Labs for Rectangle Packager
*/


/* auto-generated This file was generated by a T4 template. Don't change it directly as your change would get overwritten.  Instead, make changes
to the .tt file (i.e. the T4 template) and save it to regenerate this file. */
namespace MvcApp.Content.Images
{
    public static class SpriteVar
    {
        public const string t4accept = "t4accept";
        public const string t4add = "t4add";
        public const string t4block = "t4block";
        public const string t4calendar = "t4calendar";
        public const string t4chart = "t4chart";
        public const string t4clock = "t4clock";
        public const string t4folder_full = "t4folder_full";
        public const string t4heart = "t4heart";
        public const string t4help = "t4help";
        public const string t4mail = "t4mail";
        public const string t4refresh = "t4refresh";
        public const string t4rss = "t4rss";
        public const string t4search = "t4search";
        public const string t4search_page = "t4search_page";
        public const string t4unlock = "t4unlock";
        public const string t4user = "t4user";
        public const string t4users = "t4users";
        public const string t4warning = "t4warning";
    }
}

